name: test
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          - "5.34.1"
          - "5.16.3"
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: install modules
        run: |
          cpanm --installdeps -n .
          cpanm -n Module::Build::Tiny
      - name: build and test
        run: |
          perl Build.PL
          ./Build
          ./Build test
